services:
  config-server:
    build: ./config-server
    image: config-server
    platform: linux/x86_64
    container_name: config-server
    ports:
      - "8071:8071"
  eureka-server:
    build: ./eureka-server
    image: eureka-server
    platform: linux/x86_64
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      - config-server
    restart: on-failure

  item-service:
    build: ./item
    image: item
    platform: linux/x86_64
    container_name: item
    ports:
      - "9090:9090"
    depends_on:
      - item-db
      - config-server
    restart: on-failure

  thing-service:
    build: ./thing
    image: thing
    platform: linux/x86_64
    container_name: thing
    ports:
      - "8080:8080"
    depends_on:
      - thing-db
      - config-server
    restart: on-failure

  thing-service2:
    build: ./thing
    image: thing2
    platform: linux/x86_64
    container_name: thing2
    ports:
      - "8081:8081"
    depends_on:
      - thing-db
      - config-server
    restart: on-failure

  item-db:
    image: postgres:13.7-alpine
    container_name: item-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=item
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  thing-db:
    image: postgres:13.7-alpine
    container_name: thing-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=thing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

#  vault здесь только для тестов, в девмоде. Настройки по прежнему подтянутся из yaml
#  vault:
#    image: vault:1.13.3
#    container_name: vault
#    ports:
#      - "8200:8200"
#    restart: unless-stopped
#    volumes:
#      - ./logs:/vault/logs
#      - ./file:/vault/file
#      - ./config:/vault/config
#    cap_add:
#      - IPC_LOCK
