spring:
  application:
    name: item
  profiles:
    active: prod
  config:
    import: optional:configserver:http://config-server:8071
#  cloud:
#    function:
#      definition: processNewItemMessage
#
#
#
#
#
#  kafka:
#    bootstrap-servers: kafka:9092

item:
  example: "default"
#
#logging:
#  level:
#    kafka: debug



